services:
  migration:
    image: misdata:latest
    profiles: [initialize]
    env_file:
      - .env
    command: bash -c "python manage.py makemigrations && python manage.py migrate"
    networks:
      - misdata

  app:
    image: misdata:latest
    ports:
      - 8005:8000
    env_file:
      - .env
    restart: always
    volumes:
      - ./:/app
      - /var/backup/filematch:/app/media
    networks:
      - misdata

networks:
  misdata: